USE Candles;
GO
ALTER TABLE Customers WITH CHECK
ADD CONSTRAINT FK_Zip FOREIGN KEY(Zip) REFERENCES Zipcode (ZipID)
ON UPDATE CASCADE
GO
ALTER TABLE Sales WITH CHECK
ADD CONSTRAINT FK_LocationID FOREIGN KEY(LocationID) REFERENCES SalesLocation (LocationID)
ON UPDATE CASCADE
GO
ALTER TABLE Sales WITH CHECK
ADD CONSTRAINT FK_CustomerID FOREIGN KEY(CustomerID) REFERENCES Customers(CustomerID)
ON UPDATE CASCADE
GO
ALTER TABLE OrderDetails WITH CHECK
ADD CONSTRAINT FK_SalesID FOREIGN KEY(SalesID) REFERENCES Sales(SalesID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE OrderDetails WITH CHECK
ADD CONSTRAINT FK_InventoryID FOREIGN KEY(InventoryID) REFERENCES Inventory(InventoryID)
ON UPDATE CASCADE
GO
